/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectmedidemo1;

import java.awt.Component;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author shati
 */
public class FirstInfoFrame extends javax.swing.JFrame {

    /**
     * Creates new form FirstInfoFrame
     */
    protected String tdata [][]= new String [1000][1];
    protected int rowcount=0;
    public String name="";
    
    
    
    
    public FirstInfoFrame() {
        initComponents();
        jButtonLoadUserName.doClick();
    }
    public void loadDoClick()
        {
        jButtonLoadUserName.doClick();
        }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableUserNames = new javax.swing.JTable();
        jButtonAddUser = new javax.swing.JButton();
        jButtonDeleteUser = new javax.swing.JButton();
        jButtonLoadUserName = new javax.swing.JButton();
        jButtonUpdate = new javax.swing.JButton();
        jTextFieldUpdateInfo = new javax.swing.JTextField();
        jTextFieldDeleteUser = new javax.swing.JTextField();
        jButtonClear = new javax.swing.JButton();
        jTextFieldUserName = new javax.swing.JTextField();
        jLabelUserName = new javax.swing.JLabel();
        jButtonLogIn = new javax.swing.JButton();
        jButtonSetAlarm = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 500));

        jTableUserNames.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name"
            }
        ));
        jScrollPane1.setViewportView(jTableUserNames);

        jButtonAddUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/plus.png"))); // NOI18N
        jButtonAddUser.setText("ADD USER");
        jButtonAddUser.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonAddUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddUserActionPerformed(evt);
            }
        });

        jButtonDeleteUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/delete.png"))); // NOI18N
        jButtonDeleteUser.setText("DELTE USER");
        jButtonDeleteUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteUserActionPerformed(evt);
            }
        });

        jButtonLoadUserName.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/loading.png"))); // NOI18N
        jButtonLoadUserName.setText("Load ");
        jButtonLoadUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoadUserNameActionPerformed(evt);
            }
        });

        jButtonUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/update.png"))); // NOI18N
        jButtonUpdate.setText("UPDATE INFO");
        jButtonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateActionPerformed(evt);
            }
        });

        jTextFieldUpdateInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUpdateInfoActionPerformed(evt);
            }
        });

        jButtonClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/clear.png"))); // NOI18N
        jButtonClear.setText("Clear");
        jButtonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearActionPerformed(evt);
            }
        });

        jTextFieldUserName.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabelUserName.setText("Username :");

        jButtonLogIn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/man-user.png"))); // NOI18N
        jButtonLogIn.setText("Log In");
        jButtonLogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogInActionPerformed(evt);
            }
        });

        jButtonSetAlarm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/alarm.png"))); // NOI18N
        jButtonSetAlarm.setText("SET ALARM");
        jButtonSetAlarm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSetAlarmActionPerformed(evt);
            }
        });

        jLabel1.setText(":");

        jLabel2.setText(":");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addComponent(jButtonSetAlarm)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonAddUser, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(jLabel1)
                        .addGap(4, 4, 4)
                        .addComponent(jTextFieldUpdateInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonDeleteUser, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(jLabel2)
                        .addGap(4, 4, 4)
                        .addComponent(jTextFieldDeleteUser, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonLogIn)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelUserName)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(130, 130, 130)
                                .addComponent(jButtonClear))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonLoadUserName)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(6, 6, 6))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jButtonLoadUserName)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonLogIn)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jButtonClear)))
                        .addGap(75, 75, 75)
                        .addComponent(jButtonAddUser)
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonUpdate)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jTextFieldUpdateInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonDeleteUser)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jTextFieldDeleteUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jButtonSetAlarm))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonLoadUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoadUserNameActionPerformed
        // TODO add your handling code here:
        //jTableUserNames.repaint();
        //DefaultTableModel tmodel=(DefaultTableModel)jTableUserNames.getModel(); 
        try
        {        
                jButtonClear.doClick();
                DBConnectUserInfo dbc = new DBConnectUserInfo();
                ResultSet rs = dbc.getResultUserName();
                while(rs.next())
                {
                    String cols[]={"Name"};
                    tdata[rowcount][0]=rs.getString("name");                
                    rowcount ++;
                    DefaultTableModel tmodel=(DefaultTableModel)jTableUserNames.getModel();                
                    tmodel.setDataVector(tdata, cols);
                System.out.println("Rowcount "+rowcount);
                    
                }
                for(int i=0;i<=rowcount;i++)
                    {
                    //tmodel.removeRow(i);
                    tdata[i][0]="";
                    //rowcount--;
                    String cols[]={"Name"};
                    //DefaultTableModel tmodel=(DefaultTableModel)jTableUserNames.getModel();                
                    //tmodel.setDataVector(tdata, cols);
                    //System.out.println("Rowcount "+rowcount);
                    }
                    
                
        }
        catch(Exception e)
        {
            System.out.println("Error:" +e);
            e.printStackTrace();                    
        }
        
        
    }//GEN-LAST:event_jButtonLoadUserNameActionPerformed

    private void jButtonAddUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddUserActionPerformed
        // TODO add your handling code here:
        AddUserInfo UI = new AddUserInfo();
        UI.setVisible(true);
        jButtonClear.doClick();
        jButtonLoadUserName.doClick();
        dispose();
        
    }//GEN-LAST:event_jButtonAddUserActionPerformed

    private void jButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateActionPerformed
        // TODO add your handling code here:       
        DBConnectUserInfo DBC = new DBConnectUserInfo();
        ResultSet rs=DBC.getResultSet(jTextFieldUpdateInfo.getText());
        try {
            if(rs.next()==false)
            {
            System.out.println("No User");
            JOptionPane.showMessageDialog(null,"No User of this name");    
                
            }
            
            else
            {
                UserInfoUpdate UIU = new UserInfoUpdate();
                UIU.passUserName(jTextFieldUpdateInfo.getText());
                UIU.setVisible(true);
                this.dispose();
                jButtonClear.doClick();
                jButtonLoadUserName.doClick();
            }
        } catch (SQLException ex) {
            Logger.getLogger(FirstInfoFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
               
    }//GEN-LAST:event_jButtonUpdateActionPerformed

    private void jButtonDeleteUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteUserActionPerformed
        // TODO add your handling code here:
        String UserName = jTextFieldDeleteUser.getText();
        DBConnectUserInfo DC = new DBConnectUserInfo();
        DC.deleteUser(UserName);
        
        
        
        jButtonLoadUserName.doClick();
        
    }//GEN-LAST:event_jButtonDeleteUserActionPerformed

    private void jButtonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearActionPerformed
        // TODO add your handling code here:
        rowcount = 0;
        String cols[]={"Name"};
         DefaultTableModel tmodel=(DefaultTableModel)jTableUserNames.getModel();                
        tmodel.setDataVector(tdata, cols);
    }//GEN-LAST:event_jButtonClearActionPerformed

    private void jButtonLogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogInActionPerformed
        // TODO add your handling code here:
        DBConnectUserInfo DBC = new DBConnectUserInfo();
        ResultSet rs=DBC.getResultSet(jTextFieldUserName.getText());
        try {
            if(rs.next()==false)
            {
            System.out.println("No User");
            JOptionPane.showMessageDialog(null,"No User of this name");     
            }
            
            else{            
                UserAndMedicineFrame UMF = new UserAndMedicineFrame();
                UMF.passUsername(jTextFieldUserName.getText());
                UMF.setVisible(true);
                dispose();
            }
        } catch (SQLException ex) {
            Logger.getLogger(FirstInfoFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButtonLogInActionPerformed

    private void jButtonSetAlarmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSetAlarmActionPerformed
        // TODO add your handling code here:
        
       SetAlarmFrame SAF = new SetAlarmFrame();
       SAF.setAlarmText();
       SAF.setVisible(true);
    }//GEN-LAST:event_jButtonSetAlarmActionPerformed

    private void jTextFieldUpdateInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUpdateInfoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUpdateInfoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FirstInfoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FirstInfoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FirstInfoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FirstInfoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FirstInfoFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddUser;
    private javax.swing.JButton jButtonClear;
    private javax.swing.JButton jButtonDeleteUser;
    private javax.swing.JButton jButtonLoadUserName;
    private javax.swing.JButton jButtonLogIn;
    private javax.swing.JButton jButtonSetAlarm;
    private javax.swing.JButton jButtonUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelUserName;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableUserNames;
    private javax.swing.JTextField jTextFieldDeleteUser;
    private javax.swing.JTextField jTextFieldUpdateInfo;
    private javax.swing.JTextField jTextFieldUserName;
    // End of variables declaration//GEN-END:variables
}
