/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectmedidemo1;

import java.sql.ResultSet;
import java.util.ArrayList;

/**
 *
 * @author shati
 */

public class UpdateMedicineFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewMedicineFrame
     */
    private ResultSet rs;
    public void getName(String mName,String uName)
    {
    jLabelMNU.setText(mName);
    jLabelUNU.setText(uName);
    try
            {
            DBConnectMedicineInformation DBC = new  DBConnectMedicineInformation();
            ResultSet rs=DBC.getResultMnN(jLabelMNU.getText(),jLabelUNU.getText());
            //System.out.println(rs);
            while(rs.next())
                {
                //String medName=rs.getString("medname");
                //String userName=rs.getString("username");
                String mCount=rs.getString("count");
                String mAlarm=rs.getString("morningalarm");
                String dAlarm=rs.getString("dayalarm");
                String nAlarm=rs.getString("nightalarm");                
                System.out.println(mCount);
                System.out.println(mAlarm); 
                System.out.println(dAlarm); 
                System.out.println(nAlarm); 
                jTextFieldCount.setText(mCount);
                if(mAlarm.equals("ON"))
                    {
                    jCheckBoxMorning.setSelected(true);
                    }
                if(dAlarm.equals("ON"))
                    {
                    jCheckBoxDay.setSelected(true);
                    }
                if(nAlarm.equals("ON"))
                    {
                    jCheckBoxNight.setSelected(true);
                    }
                }
            }
            catch(Exception e)
                    {
                System.out.println("Error:" +e);
                e.printStackTrace();                    
                    }
    
    }
    public UpdateMedicineFrame() {
        initComponents();
    }
    public void setName(String name)
        {
        jLabelUNU.setText(name);
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelMedicineName = new javax.swing.JLabel();
        jLabelUserName = new javax.swing.JLabel();
        jLabelCount = new javax.swing.JLabel();
        jTextFieldCount = new javax.swing.JTextField();
        jLabelAlarm = new javax.swing.JLabel();
        jCheckBoxMorning = new javax.swing.JCheckBox();
        jCheckBoxDay = new javax.swing.JCheckBox();
        jCheckBoxNight = new javax.swing.JCheckBox();
        jButtonUpdate = new javax.swing.JButton();
        jLabelMNU = new javax.swing.JLabel();
        jLabelUNU = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelMedicineName.setText("Medicine Name:");

        jLabelUserName.setText("User Name:");

        jLabelCount.setText("Count:");

        jLabelAlarm.setText("Alarm:");

        jCheckBoxMorning.setText("Morning");

        jCheckBoxDay.setText("Day");

        jCheckBoxNight.setText("Night");

        jButtonUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/update_1.png"))); // NOI18N
        jButtonUpdate.setText("UPDATE");
        jButtonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateActionPerformed(evt);
            }
        });

        jLabelMNU.setText("Med Name");

        jLabelUNU.setText("User Name");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButtonUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelAlarm)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCheckBoxMorning)
                        .addGap(18, 18, 18)
                        .addComponent(jCheckBoxDay)
                        .addGap(18, 18, 18)
                        .addComponent(jCheckBoxNight))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelUserName)
                            .addComponent(jLabelMedicineName)
                            .addComponent(jLabelCount))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldCount)
                            .addComponent(jLabelMNU, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelUNU, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE))
                        .addGap(15, 15, 15)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMedicineName)
                    .addComponent(jLabelMNU))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelUserName)
                    .addComponent(jLabelUNU))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCount)
                    .addComponent(jTextFieldCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAlarm)
                    .addComponent(jCheckBoxMorning)
                    .addComponent(jCheckBoxDay)
                    .addComponent(jCheckBoxNight))
                .addGap(18, 18, 18)
                .addComponent(jButtonUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateActionPerformed
        // TODO add your handling code here:
        ArrayList mInfo = new ArrayList();
        mInfo.add(jLabelMNU.getText());
        mInfo.add(jLabelUNU.getText());
        mInfo.add(jTextFieldCount.getText());
        if(jCheckBoxMorning.isSelected())
            {
            mInfo.add("ON");
            }
        else{
            mInfo.add("OFF");
            }
        
        if(jCheckBoxDay.isSelected())
            {
            mInfo.add("ON");
            }
        else{
            mInfo.add("OFF");
            }
        
        if(jCheckBoxNight.isSelected())
            {
            mInfo.add("ON");
            }
        else{
            mInfo.add("OFF");
            }
        DBConnectMedicineInformation DBCMI = new DBConnectMedicineInformation ();
        DBCMI.updateMedInfo(mInfo,jLabelMNU.getText(),jLabelUNU.getText());
        System.out.println(mInfo);
        dispose();
        
    }//GEN-LAST:event_jButtonUpdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateMedicineFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateMedicineFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateMedicineFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateMedicineFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateMedicineFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonUpdate;
    private javax.swing.JCheckBox jCheckBoxDay;
    private javax.swing.JCheckBox jCheckBoxMorning;
    private javax.swing.JCheckBox jCheckBoxNight;
    private javax.swing.JLabel jLabelAlarm;
    private javax.swing.JLabel jLabelCount;
    private javax.swing.JLabel jLabelMNU;
    private javax.swing.JLabel jLabelMedicineName;
    private javax.swing.JLabel jLabelUNU;
    private javax.swing.JLabel jLabelUserName;
    private javax.swing.JTextField jTextFieldCount;
    // End of variables declaration//GEN-END:variables
}
