/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectmedidemo1;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author shati
 */
public class UserAndMedicineFrame extends javax.swing.JFrame {

    /**
     * Creates new form UserAndMedicineFrame
     */
    private ResultSet rs;
    private ResultSet rs2;
    protected String tdata [][]= new String [1000][3];
    protected int tdatarowcount=0;
    protected String mdata [][]= new String [1000][6];
    protected int mdatarowcount=0;
    public UserAndMedicineFrame() {
        
        initComponents();
    }
    public void passUsername(String name)
        {
        jLabelUNM.setText(name);
        try
            {
            DBConnectUserInfo DBC = new DBConnectUserInfo();
            ResultSet rs=DBC.getResultSet(name);
            //System.out.println(rs);
            
            while(rs.next())
                {
                String uName=rs.getString("name");
                String uAge=rs.getString("age");
                String uGender=rs.getString("gender");
                String uBloodGroup=rs.getString("bloodgroup");
                String ucols[]={"Age","Gender","BloodGroup"};
                DefaultTableModel tmodel=(DefaultTableModel)jTableUserInfo.getModel();
                
                tdata[tdatarowcount][0]=uAge;
                tdata[tdatarowcount][1]=uGender;
                tdata[tdatarowcount][2]=uBloodGroup;
                //tdata[rowcount][3]=jTextField4.getText();
                
                tmodel.setDataVector(tdata, ucols);
                tdatarowcount++;    
                jButtonLoad.doClick(); 
                
                
                
                }
            }
            catch(Exception e)
                    {
                System.out.println("Error:" +e);
                e.printStackTrace();                    
                    }
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableUserInfo = new javax.swing.JTable();
        jLabelName = new javax.swing.JLabel();
        jLabelMedicineInfo = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableMedicineInfo = new javax.swing.JTable();
        jButtonAddMed = new javax.swing.JButton();
        jButtonDeleteMed = new javax.swing.JButton();
        jButtonAddCount = new javax.swing.JButton();
        jTextFieldDeleteMed = new javax.swing.JTextField();
        jTextFieldUpdateMed = new javax.swing.JTextField();
        jButtonLoad = new javax.swing.JButton();
        jButtonClear = new javax.swing.JButton();
        jLabelUNM = new javax.swing.JLabel();
        jButtonBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTableUserInfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "Age", "Gender", "Blood Group"
            }
        ));
        jScrollPane1.setViewportView(jTableUserInfo);

        jLabelName.setText("   Name:");
        jLabelName.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelMedicineInfo.setText("Medicine Info");
        jLabelMedicineInfo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabelMedicineInfo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jTableMedicineInfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Medname", "User", "Count", "Morning Alarm", "Day Alarm", "Night Alarm"
            }
        ));
        jScrollPane2.setViewportView(jTableMedicineInfo);

        jButtonAddMed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/plus.png"))); // NOI18N
        jButtonAddMed.setText("Add New Medicine");
        jButtonAddMed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddMedActionPerformed(evt);
            }
        });

        jButtonDeleteMed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/delete.png"))); // NOI18N
        jButtonDeleteMed.setText("Delete Medicine");
        jButtonDeleteMed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteMedActionPerformed(evt);
            }
        });

        jButtonAddCount.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/update_1.png"))); // NOI18N
        jButtonAddCount.setText("Update Med Info");
        jButtonAddCount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddCountActionPerformed(evt);
            }
        });

        jButtonLoad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/loading.png"))); // NOI18N
        jButtonLoad.setText("LOAD");
        jButtonLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoadActionPerformed(evt);
            }
        });

        jButtonClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/clear.png"))); // NOI18N
        jButtonClear.setText("CLEAR");
        jButtonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearActionPerformed(evt);
            }
        });

        jLabelUNM.setText("User Name");

        jButtonBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/back.png"))); // NOI18N
        jButtonBack.setText("Back");
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jButtonAddCount, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                                            .addComponent(jButtonDeleteMed, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jTextFieldDeleteMed)
                                            .addComponent(jTextFieldUpdateMed, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addComponent(jButtonBack)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jButtonClear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jButtonLoad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(78, 78, 78)
                                .addComponent(jButtonAddMed, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 131, Short.MAX_VALUE)))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jLabelName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelUNM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(110, 110, 110))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelMedicineInfo)
                .addGap(235, 235, 235))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelName, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelUNM, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(jLabelMedicineInfo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonAddMed)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonDeleteMed)
                            .addComponent(jTextFieldDeleteMed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonAddCount)
                            .addComponent(jTextFieldUpdateMed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonLoad)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonClear)
                            .addComponent(jButtonBack))))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAddMedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddMedActionPerformed
        // TODO add your handling code here:
        NewMedicineFrame NMF = new NewMedicineFrame();
        NMF.setName(jLabelUNM.getText());
        NMF.setVisible(true);        
        
    }//GEN-LAST:event_jButtonAddMedActionPerformed

    private void jButtonAddCountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddCountActionPerformed
        // TODO add your handling code here:
        DBConnectMedicineInformation DBC = new  DBConnectMedicineInformation();
        ResultSet rs=DBC.getResultMnN(jTextFieldUpdateMed.getText(),jLabelUNM.getText());
        try {
            if(rs.next()==false)
            {
            System.out.println("No Medicine");
            JOptionPane.showMessageDialog(null,"No Data of this medicine");    
            
            
            }
            else
            {
                
                UpdateMedicineFrame UMF = new UpdateMedicineFrame();
                UMF.setVisible(true);
                UMF.getName(jTextFieldUpdateMed.getText(), jLabelUNM.getText());
            }
        } catch (SQLException ex) {
            Logger.getLogger(UserAndMedicineFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonAddCountActionPerformed

    private void jButtonLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoadActionPerformed
        // TODO add your handling code here:
        //jButtonLoad.doClick();
        try
            {
            jButtonClear.doClick();
            DBConnectMedicineInformation DBCMI = new DBConnectMedicineInformation();
            ResultSet rs2=DBCMI.getResultSet(jLabelUNM.getText());
            //System.out.println(rs);
            while(rs2.next())
                {              
                         
                mdata[mdatarowcount][0]=rs2.getString("medname");
                mdata[mdatarowcount][1]=rs2.getString("username");
                mdata[mdatarowcount][2]=rs2.getString("count");
                mdata[mdatarowcount][3]=rs2.getString("morningalarm");
                mdata[mdatarowcount][4]=rs2.getString("dayalarm");
                mdata[mdatarowcount][5]=rs2.getString("nightalarm");
                String mcols[]={"Medname","Username","Count","Morningalarm","Dayalarm","Nightalarm"};
                mdatarowcount++;  
                DefaultTableModel mmodel=(DefaultTableModel)jTableMedicineInfo.getModel(); 
                mmodel.setDataVector(mdata, mcols);                                
                
                }
                for(int i=0;i<=mdatarowcount;i++)
                    {
                    mdata[i][0]=null;
                    mdata[i][1]=null;
                    mdata[i][2]=null;
                    mdata[i][3]=null;
                    mdata[i][4]=null;
                    mdata[i][5]=null;
                    //mdata[i][6]=null;
                    }
                mdatarowcount=0;
                
            }
            catch(Exception e)
                    {
                System.out.println("Error:" +e);
                e.printStackTrace();                    
                    }
        
    }//GEN-LAST:event_jButtonLoadActionPerformed

    private void jButtonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearActionPerformed
        // TODO add your handling code here:        
        mdatarowcount=0;
        String mcols[]={"Medname","Username","Count","Morningalarm","Dayalarm","Nightalarm"};
                //mdatarowcount++;  
                DefaultTableModel mmodel=(DefaultTableModel)jTableMedicineInfo.getModel(); 
                mmodel.setDataVector(mdata, mcols);
    }//GEN-LAST:event_jButtonClearActionPerformed

    private void jButtonDeleteMedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteMedActionPerformed
        // TODO add your handling code here:
        String uName=jLabelUNM.getText();
        String mName=jTextFieldDeleteMed.getText();
        DBConnectMedicineInformation DBMI= new DBConnectMedicineInformation();
        DBMI.deleteMed(uName,mName);
        jButtonLoad.doClick();
    }//GEN-LAST:event_jButtonDeleteMedActionPerformed

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        // TODO add your handling code here:
        FirstInfoFrame FI = new FirstInfoFrame();
        FI.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_jButtonBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserAndMedicineFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserAndMedicineFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserAndMedicineFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserAndMedicineFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserAndMedicineFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddCount;
    private javax.swing.JButton jButtonAddMed;
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonClear;
    private javax.swing.JButton jButtonDeleteMed;
    private javax.swing.JButton jButtonLoad;
    private javax.swing.JLabel jLabelMedicineInfo;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelUNM;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableMedicineInfo;
    private javax.swing.JTable jTableUserInfo;
    private javax.swing.JTextField jTextFieldDeleteMed;
    private javax.swing.JTextField jTextFieldUpdateMed;
    // End of variables declaration//GEN-END:variables
}
